"""
Patches android/app/build.gradle.kts (freshly generated by `flutter create`)
to sign release builds with the real upload key instead of the debug key.

Reads keystore details from android/key.properties (written separately by
the CI workflow from GitHub Secrets — never committed to the repo).

Written defensively: every insertion is verified immediately after, and the
script raises a clear error and exits non-zero if an expected anchor isn't
found, rather than silently leaving the release build debug-signed.
"""
import re
import sys

GRADLE_PATH = "android/app/build.gradle.kts"

IMPORTS = (
    'import java.util.Properties\n'
    'import java.io.FileInputStream\n'
)

PROPERTIES_LOADER = '''
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}
'''

SIGNING_CONFIG_BLOCK = '''
    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = keystoreProperties["storeFile"]?.let { file(it) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }
'''


def fail(message: str):
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def main():
    with open(GRADLE_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    if "keystorePropertiesFile" in content:
        print("build.gradle.kts already patched, skipping.")
        return

    # 1) Prepend imports + properties loader at the very top of the file.
    content = IMPORTS + PROPERTIES_LOADER + "\n" + content

    # 2) Insert the release signingConfigs block right after the `android {` opener.
    new_content, count = re.subn(
        r"(android\s*\{)",
        lambda m: m.group(1) + "\n" + SIGNING_CONFIG_BLOCK,
        content,
        count=1,
    )
    if count != 1:
        fail("Could not find 'android {' block to insert signingConfigs into.")
    content = new_content

    # 3) Point the release buildType at our new signing config instead of debug's.
    new_content, count = re.subn(
        r'signingConfig\s*=\s*signingConfigs\.getByName\("debug"\)',
        'signingConfig = signingConfigs.getByName("release")',
        content,
        count=1,
    )
    if count != 1:
        fail(
            "Could not find the default debug signingConfig line in the release "
            "buildType to replace. The Flutter Gradle template may have changed — "
            "check android/app/build.gradle.kts manually."
        )
    content = new_content

    with open(GRADLE_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print("build.gradle.kts patched: release builds now sign with the upload key.")


if __name__ == "__main__":
    main()
