"""
Patches android/app/src/main/AndroidManifest.xml (freshly generated by
`flutter create .`) to:
  1. Add the camera + internet permissions Sufra needs.
  2. Set the app's display name to the Arabic "سُفرة" — either directly on
     the <application android:label=...> attribute, or via strings.xml if
     the generated manifest references @string/app_name instead.

Written defensively (regex-based, idempotent) because the exact manifest
boilerplate Flutter generates changes slightly between SDK versions.
"""
import re
import os

MANIFEST_PATH = "android/app/src/main/AndroidManifest.xml"
STRINGS_PATH = "android/app/src/main/res/values/strings.xml"
APP_NAME = "سُفرة"

PERMISSIONS = [
    '    <uses-permission android:name="android.permission.CAMERA"/>',
    '    <uses-permission android:name="android.permission.INTERNET"/>',
    '    <uses-feature android:name="android.hardware.camera" android:required="true"/>',
]


def add_permissions(xml: str) -> str:
    if "android.permission.CAMERA" in xml:
        return xml  # already patched
    return re.sub(
        r"(<manifest[^>]*>)",
        lambda m: m.group(1) + "\n" + "\n".join(PERMISSIONS),
        xml,
        count=1,
    )


def set_app_label(xml: str) -> str:
    label_match = re.search(r'android:label="([^"]*)"', xml)
    if not label_match:
        return xml

    current_label = label_match.group(1)
    if current_label.startswith("@string/"):
        # App name lives in strings.xml — write/update it there instead.
        string_name = current_label.replace("@string/", "")
        write_strings_xml(string_name)
        return xml

    return xml.replace(f'android:label="{current_label}"', f'android:label="{APP_NAME}"')


def write_strings_xml(string_name: str):
    os.makedirs(os.path.dirname(STRINGS_PATH), exist_ok=True)
    if os.path.exists(STRINGS_PATH):
        with open(STRINGS_PATH, "r", encoding="utf-8") as f:
            content = f.read()
        if f'name="{string_name}"' in content:
            content = re.sub(
                rf'(<string name="{string_name}">)[^<]*(</string>)',
                rf"\1{APP_NAME}\2",
                content,
            )
        else:
            content = content.replace(
                "</resources>", f'    <string name="{string_name}">{APP_NAME}</string>\n</resources>'
            )
    else:
        content = (
            '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
            f'    <string name="{string_name}">{APP_NAME}</string>\n</resources>\n'
        )
    with open(STRINGS_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        xml = f.read()

    xml = add_permissions(xml)
    xml = set_app_label(xml)

    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        f.write(xml)

    print("AndroidManifest.xml patched: permissions added, app label set to", APP_NAME)


if __name__ == "__main__":
    main()
